spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: pwd

server:
  port: 8080

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %X%n%wEx"

app:
  integration:
    product-info-service:
      url: http://localhost:8082
      base-path: /productInfoService
    order-search-service:
      url: http://localhost:8081
      base-path: /orderSearchService