spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: your_database_name

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

app:
  user-info:
    tot-init-users: 10
  integration:
    product-info-service:
      url: http://localhost:8082
      base-path: /productInfoService
    order-search-service:
      url: http://localhost:8081
      base-path: /orderSearchService