spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

server:
  port: 8080

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %X%n%wEx"

app:
  integration:
    product-info-service:
      url: ${PRODUCT_INFO_SERVICE_URL}
      base-path: /productInfoService
    order-search-service:
      url: ${ORDER_SEARCH_SERVICE_URL}
      base-path: /orderSearchService